version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    environment:
        - TZ=Europe/Moscow
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: evgenferrum/prosept_backend:latest
    environment:
        - TZ=Europe/Moscow
    restart: always
    command: "sh -c 'alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000'"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
     - db
    env_file:
      - ./.env
  
  frontend:
    image: evgenferrum/prosept_frontend:latest
    environment:
        - TZ=Europe/Moscow
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  
  ds:
    image: evgenferrum/prosept_ds:latest
    environment:
        - TZ=Europe/Moscow
    restart: always
    depends_on:
      - frontend

  nginx:
    image: nginx:1.21.3
    environment:
        - TZ=Europe/Moscow
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - ds

volumes:
  static_value:
  media_value:
  db_data: