"""init

Revision ID: c0d3430d2ddc
Revises: f70a0c0ac3bf
Create Date: 2023-12-02 22:34:14.195039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d3430d2ddc'
down_revision = 'f70a0c0ac3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
